# Generated by Django 2.2.6 on 2023-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(default='', max_length=255)),
                ('album', models.CharField(default='', max_length=255)),
                ('genre', models.CharField(default='', max_length=255)),
                ('year', models.CharField(default='', max_length=255)),
                ('lyrics', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('fs_id', models.CharField(default='', max_length=255)),
                ('path', models.CharField(default='', max_length=255)),
                ('parent_path', models.CharField(default='', max_length=255)),
                ('size', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
