# Generated by Django 2.2.6 on 2023-05-10 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
