# Generated by Django 2.2.6 on 2023-04-26 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_scan_time', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(default='folder', max_length=32)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('parent_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
