# Generated by Django 2.2.6 on 2023-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
