# Generated by Django 2.2.6 on 2023-05-19 13:22

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_folder_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='accessed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='访问时间'),
        ),
        migrations.AlterField(
            model_name='album',
            name='all_artist_ids',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='external_info_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='external_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='mbz_album_artist_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='mbz_album_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='mbz_album_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='mbz_album_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
