# Generated by Django 2.2.6 on 2023-04-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20230426_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='mbz_album_artist_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbz_album_comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbz_album_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbz_album_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbz_artist_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbz_release_track_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbz_track_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
