# Generated by Django 2.2.6 on 2023-04-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20230426_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='large_image_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='medium_image_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='order_artist_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='small_image_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='sort_artist_name',
        ),
    ]
