# Generated by Django 2.2.6 on 2023-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20230427_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
