# Generated by Django 2.2.6 on 2023-06-09 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20230519_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': '文件目录', 'verbose_name_plural': '文件目录'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': '播放列表', 'verbose_name_plural': '播放列表'},
        ),
        migrations.AlterModelOptions(
            name='trackfavorite',
            options={'ordering': ('-creation_date',), 'verbose_name': '喜爱列表', 'verbose_name_plural': '喜爱列表'},
        ),
        migrations.AlterField(
            model_name='folder',
            name='file_type',
            field=models.CharField(choices=[('folder', '文件夹'), ('music', '音乐'), ('image', '图片')], default='folder', max_length=32, verbose_name='文件格式'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=256, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='state',
            field=models.CharField(choices=[('none', '未扫描'), ('scanning', '扫描中'), ('scanned', '扫描完成'), ('updated', '已更新')], default='none', max_length=32, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='music.Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='music.Track')),
            ],
            options={
                'ordering': ('-playlist', 'index'),
            },
        ),
    ]
