# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.2 on 2018-01-09 18:25


from django.db import migrations
import pipeline.engine.models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processsnapshot",
            name="data",
            field=pipeline.engine.models.IOField(verbose_name="pipeline \u8fd0\u884c\u65f6\u6570\u636e"),
        ),
    ]
