# Generated by Django 2.2.6 on 2022-02-10 14:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='UUID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='节点描述')),
                ('show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('top', models.IntegerField(default=300)),
                ('left', models.IntegerField(default=300)),
                ('ico', models.CharField(blank=True, max_length=64, null=True, verbose_name='icon')),
                ('fail_retry_count', models.IntegerField(default=0, verbose_name='失败重试次数')),
                ('fail_offset', models.IntegerField(default=0, verbose_name='失败重试间隔')),
                ('fail_offset_unit', models.CharField(choices=[('seconds', '秒'), ('hours', '时'), ('minutes', '分')], max_length=32, verbose_name='重试间隔单位')),
                ('node_type', models.IntegerField(default=2)),
                ('component_code', models.CharField(max_length=255, verbose_name='插件名称')),
                ('is_skip_fail', models.BooleanField(default=False, verbose_name='忽略失败')),
                ('is_timeout_alarm', models.BooleanField(default=False, verbose_name='超时告警')),
                ('inputs', django_mysql.models.JSONField(default=dict, verbose_name='输入参数')),
                ('outputs', django_mysql.models.JSONField(default=dict, verbose_name='输出参数')),
                ('template_type', models.CharField(default='2', max_length=1, verbose_name='节点模板类型')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
