# Generated by Django 2.2.6 on 2022-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_nodetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='content',
            field=models.IntegerField(default=0, verbose_name='模板id'),
        ),
        migrations.AddField(
            model_name='noderun',
            name='content',
            field=models.IntegerField(default=0, verbose_name='模板id'),
        ),
        migrations.AddField(
            model_name='nodetemplate',
            name='content',
            field=models.IntegerField(default=0, verbose_name='模板id'),
        ),
    ]
