# Generated by Django 2.2.6 on 2022-02-26 12:02

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20220210_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplate',
            name='inputs_component',
            field=django_mysql.models.JSONField(default=list, verbose_name='前端参数组件'),
        ),
        migrations.AddField(
            model_name='nodetemplate',
            name='outputs_component',
            field=django_mysql.models.JSONField(default=list, verbose_name='前端参数组件'),
        ),
    ]
