# Generated by Django 2.2.6 on 2022-02-25 15:31

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20220210_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplate',
            name='input_component',
            field=django_mysql.models.JSONField(default=list, verbose_name='前端输入参数组件'),
        ),
        migrations.AddField(
            model_name='nodetemplate',
            name='output_component',
            field=django_mysql.models.JSONField(default=list, verbose_name='前端输出参数组件'),
        ),
    ]
