# Generated by Django 2.2.6 on 2022-06-16 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20220226_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProcessRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作业名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='作业描述')),
                ('run_type', models.CharField(max_length=32, verbose_name='调度类型')),
                ('gateways', django_mysql.models.JSONField(default=dict, verbose_name='网关信息')),
                ('constants', django_mysql.models.JSONField(default=dict, verbose_name='内部变量信息')),
                ('dag', django_mysql.models.JSONField(default=dict, verbose_name='DAG')),
                ('create_by', models.CharField(max_length=64, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('update_by', models.CharField(max_length=64, null=True, verbose_name='修改人')),
                ('root_id', models.CharField(max_length=255, verbose_name='根节点uuid')),
                ('process', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_run', to='flow.Process')),
                ('process_run', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='flow.Process')),
            ],
        ),
        migrations.CreateModel(
            name='SubNodeRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='UUID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='节点描述')),
                ('show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('top', models.IntegerField(default=300)),
                ('left', models.IntegerField(default=300)),
                ('ico', models.CharField(blank=True, max_length=64, null=True, verbose_name='icon')),
                ('fail_retry_count', models.IntegerField(default=0, verbose_name='失败重试次数')),
                ('fail_offset', models.IntegerField(default=0, verbose_name='失败重试间隔')),
                ('fail_offset_unit', models.CharField(choices=[('seconds', '秒'), ('hours', '时'), ('minutes', '分')], max_length=32, verbose_name='重试间隔单位')),
                ('node_type', models.IntegerField(default=2)),
                ('component_code', models.CharField(max_length=255, verbose_name='插件名称')),
                ('is_skip_fail', models.BooleanField(default=False, verbose_name='忽略失败')),
                ('is_timeout_alarm', models.BooleanField(default=False, verbose_name='超时告警')),
                ('inputs', django_mysql.models.JSONField(default=dict, verbose_name='输入参数')),
                ('outputs', django_mysql.models.JSONField(default=dict, verbose_name='输出参数')),
                ('content', models.IntegerField(default=0, verbose_name='模板id')),
                ('subprocess_run', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_nodes_run', to='flow.SubProcessRun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
