# Generated by Django 2.2.6 on 2022-06-16 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_subnoderun_subprocessrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noderun',
            name='process_run',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes_run', to='flow.ProcessRun'),
        ),
        migrations.AlterField(
            model_name='subnoderun',
            name='subprocess_run',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_nodes_run', to='flow.SubProcessRun'),
        ),
    ]
