# Generated by Django 2.2.6 on 2022-01-27 08:30

from django.db import migrations, models
import pipeline.django_signal_valve.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0032_templatescheme_subprocess_scheme_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.SlugField(max_length=128, verbose_name='logger 名称')),
                ('level_name', models.SlugField(max_length=32, verbose_name='日志等级')),
                ('message', models.TextField(null=True, verbose_name='日志内容')),
                ('exception', models.TextField(null=True, verbose_name='异常信息')),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='输出时间')),
                ('node_id', models.CharField(db_index=True, max_length=32, verbose_name='节点 ID')),
                ('history_id', models.IntegerField(default=-1, verbose_name='节点执行历史 ID')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_path', models.TextField(verbose_name='信号模块名')),
                ('name', models.CharField(max_length=64, verbose_name='信号属性名')),
                ('kwargs', pipeline.django_signal_valve.models.IOField(verbose_name='信号参数')),
            ],
        ),
    ]
