# Generated by Django 2.2.6 on 2023-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subsonic_api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
