# Generated by Django 2.2.6 on 2022-06-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0006_auto_20220616_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('run_type', models.CharField(choices=[('hand', '手动'), ('now', '立即'), ('time', '定时'), ('cycle', '周期'), ('cron', 'cron表达式')], max_length=64, verbose_name='执行方式')),
                ('when_start', models.CharField(max_length=100, verbose_name='执行时间')),
                ('cycle_time', models.CharField(max_length=20, null=True, verbose_name='周期时间')),
                ('cycle_type', models.CharField(choices=[('min', '分钟'), ('hour', '小时'), ('day', '天')], max_length=20, null=True, verbose_name='周期间隔(min,hour,day)')),
                ('cron_time', models.TextField(default='', verbose_name='cron表达式')),
                ('celery_task_id', models.CharField(max_length=64, null=True, verbose_name='celery的任务ID')),
                ('process_run', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flow.ProcessRun')),
            ],
        ),
    ]
