# Generated by Django 2.2.6 on 2023-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
