# Generated by Django 2.2.6 on 2023-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecord',
            name='batch',
            field=models.CharField(default='', max_length=255),
        ),
    ]
