# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0011_auto_20200217_0822"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instanceinpipeline",
            name="instance_id",
            field=models.CharField(db_index=True, max_length=255, verbose_name="实例ID"),
        ),
        migrations.AlterField(
            model_name="templateinpipeline",
            name="template_id",
            field=models.CharField(db_index=True, max_length=255, verbose_name="模板ID"),
        ),
    ]
