# -*- coding: utf-8 -*-
true = True
false = False
a = {"result": true, "code": "OK", "message": "success", "data": {"menu": [
    {"name": "home", "cnName": "首页", "to": "/home", "icon": "iconfont icon-mianxingtubiao-shouye", "hasChild": false,
     "children": []},
    {"name": "AgentList", "cnName": "Agent管理", "to": "/agentlist", "icon": "iconfont icon-mianxingtubiao-Agentguanli",
     "hasChild": true, "children": [{"name": "AgentList", "cnName": "Agent列表", "to": "/agentlist", "hasChild": false},
                                    {"name": "AgentMonitor", "cnName": "Agent监视", "to": "/agentmonitor",
                                     "hasChild": false}]},
    {"name": "NewJob", "cnName": "作业管理", "to": "/newjob", "icon": "iconfont icon-mianxingtubiao-zuoyeguanli",
     "hasChild": true, "children": [{"name": "NewJob", "cnName": "新建作业", "to": "/newjob", "hasChild": false},
                                    {"name": "JobList", "cnName": "作业列表", "to": "/joblist", "hasChild": false}]},
    {"name": "NewJobFlow", "cnName": "作业流管理", "to": "/newjobflow",
     "icon": "iconfont icon-mianxingtubiao-zuoyeliuguanli", "hasChild": true,
     "children": [{"name": "NewJobFlow", "cnName": "新建作业流", "to": "/newjobflow", "hasChild": false},
                  {"name": "JobFlowList", "cnName": "作业流列表", "to": "/jobflowlist", "hasChild": false},
                  {"name": "CalendarMgmt", "cnName": "日历管理", "to": "/calendarmgmt", "hasChild": false},
                  {"name": "VariableMgmt", "cnName": "变量管理", "to": "/variablemgmt", "hasChild": false}]},
    {"name": "JobMonitor", "cnName": "作业监视", "to": "/jobmonitor", "icon": "iconfont icon-mianxingtubiao-zuoyejiankong",
     "hasChild": false}, {"name": "LargeScreen", "cnName": "作业监视大屏", "to": "/largescreen",
                          "icon": "iconfont icon-mianxingtubiao-zuoyejiankongdaping", "hasChild": false},
    {"name": "Report", "cnName": "报表分析", "to": "/report", "icon": "iconfont icon-xianxingtubiao-shengchengbaobiao",
     "hasChild": false},
    {"name": "JobHistory", "cnName": "作业历史", "to": "/jobhistory", "icon": "iconfont icon-mianxingtubiao-zuoyelishi",
     "hasChild": false},
    {"name": "AlarmList", "cnName": "告警中心", "to": "/alarmlist", "icon": "iconfont icon-mianxingtubiao-gaojingzhongxin",
     "hasChild": false, "children": []},
    {"name": "SysSetup", "cnName": "系统管理", "to": "/syssetup", "icon": "iconfont icon-mianxingtubiao-shezhi",
     "hasChild": true, "children": [{"name": "SysSetup", "cnName": "系统设置", "to": "/syssetup", "hasChild": false},
                                    {"name": "UserAndPermissions", "cnName": "用户与权限", "to": "/userandpermissions",
                                     "hasChild": false},
                                    {"name": "SystemClassManage", "cnName": "系统类别管理", "to": "/systemclassmanage",
                                     "hasChild": false},
                                    {"name": "Log", "cnName": "操作审计", "to": "/log", "hasChild": false}]}], "router": [
    {"path": "/", "name": "home", "component": "Home", "meta": {"title": "首页"}},
    {"path": "/log", "name": "Log", "component": "Log", "meta": {"title": "操作审计"}},
    {"path": "/addcalendarmgmt", "name": "AddCalendarMgmt", "component": "AddCalendarMgmt",
     "meta": {"title": "操作日历", "back": "true", "fatherName": "CalendarMgmt"}},
    {"path": "/variablechange", "name": "variableChange", "component": "variableChange",
     "meta": {"title": "变量表", "back": "true", "fatherName": "VariableMgmt"}},
    {"path": "/singlejob", "name": "SingleJob", "component": "SingleJob",
     "meta": {"title": "单个作业", "back": "true", "fatherName": "NewJob"}},
    {"path": "/singleJobdetail", "name": "singleJobDetail", "component": "SingleJob",
     "meta": {"title": "作业管理 > 修改作业 > 单个作业"}}, {"path": "/viewdetail", "name": "ViewDetail", "component": "ViewDetail",
                                                "meta": {"title": "作业流视图详情", "back": "true",
                                                         "fatherName": "JobMonitor"}},
    {"path": "/jobflowdetail", "name": "JobFlowDetail", "component": "JobFlowDetail",
     "meta": {"title": "作业流视图历史详情", "back": "true", "fatherName": "JobHistory"}},
    {"path": "/jobviewdetail", "name": "JobViewDetail", "component": "JobViewDetail",
     "meta": {"title": "作业视图历史详情", "back": "true", "fatherName": "JobHistory"}},
    {"path": "/multiplejob", "name": "MultipleJob", "component": "MultipleJob",
     "meta": {"title": "批量作业导入", "back": "true", "fatherName": "NewJob"}},
    {"path": "/scanfile", "name": "ScanFile", "component": "ScanFile",
     "meta": {"title": "导入详情", "back": "true", "fatherName": "NewJob"}},
    {"path": "/home", "name": "home", "component": "Home", "meta": {"title": "首页"}},
    {"path": "/agentlist", "name": "AgentList", "component": "AgentList", "meta": {"title": "Agent列表"}},
    {"path": "/agentmonitor", "name": "AgentMonitor", "component": "AgentMonitor", "meta": {"title": "Agent监视"}},
    {"path": "/calendarmgmt", "name": "CalendarMgmt", "component": "CalendarMgmt", "meta": {"title": "日历管理"}},
    {"path": "/jobflowlist", "name": "JobFlowList", "component": "JobFlowList", "meta": {"title": "作业流列表"}},
    {"path": "/newjobflow", "name": "NewJobFlow", "component": "NewJobFlow", "meta": {"title": "新建作业流"}},
    {"path": "/singlejobflow", "name": "SingleJobFlow", "component": "SingleJobFlow",
     "meta": {"title": "单个作业流", "back": "true", "fatherName": "NewJobFlow"}},
    {"path": "/multiplejobflow", "name": "MultipleJobFlow", "component": "MultipleJobFlow",
     "meta": {"title": "批量导入", "back": "true", "fatherName": "NewJobFlow"}},
    {"path": "/importfile", "name": "importFile", "component": "ImportFile",
     "meta": {"title": "导入详情", "back": "true", "fatherName": "NewJobFlow"}},
    {"path": "/variablemgmt", "name": "VariableMgmt", "component": "VariableMgmt", "meta": {"title": "变量管理"}},
    {"path": "/joblist", "name": "JobList", "component": "JobList", "meta": {"title": "作业列表"}},
    {"path": "/newjob", "name": "NewJob", "component": "NewJob", "meta": {"title": "新建作业"}},
    {"path": "/jobhistory", "name": "JobHistory", "component": "JobHistory", "meta": {"title": "作业历史"}, "children": [
        {"path": "/jobflowviewhistory", "name": "JobFlowViewHistory", "component": "JobFlowViewHistory",
         "meta": {"title": "作业历史", "fatherName": "JobHistory"}},
        {"path": "/jobviewhistory", "name": "JobViewHistory", "component": "JobViewHistory",
         "meta": {"title": "作业历史", "fatherName": "JobHistory"}}]},
    {"path": "/report", "name": "Report", "component": "Report", "meta": {"title": "报表分析"}},
    {"path": "/largescreen", "name": "LargeScreen", "component": "LargeScreen", "meta": {"title": "作业监视大屏"}},
    {"path": "/jobmonitor", "name": "JobMonitor", "component": "JobMonitor", "meta": {"title": "作业监视"}, "children": [
        {"path": "/jobview", "name": "JobView", "component": "JobView",
         "meta": {"title": "作业监视", "fatherName": "JobMonitor"}},
        {"path": "/jobflowview", "name": "JobFlowView", "component": "JobFlowView",
         "meta": {"title": "作业监视", "fatherName": "JobMonitor"}}]},
    {"path": "/jobdetail", "name": "jobDetail", "component": "JobDetail",
     "meta": {"title": "作业视图详情", "back": "true", "fatherName": "JobMonitor"}},
    {"path": "/syssetup", "name": "SysSetup", "component": "SysSetup", "meta": {"title": "系统设置"}},
    {"path": "/userandpermissions", "name": "UserAndPermissions", "component": "UserAndPermissions",
     "meta": {"title": "用户与权限"}},
    {"path": "/systemclassmanage", "name": "SystemClassManage", "component": "SystemClassManage",
     "meta": {"title": "系统类别管理"}},
    {"path": "/logmange", "name": "LogMange", "component": "LogMange", "meta": {"title": "日志管理"}},
    {"path": "/alarmlist", "name": "AlarmList", "component": "AlarmList", "meta": {"title": "告警中心"}}], "permission": [
    {"url": "/agentlist", "auth": {"search": true, "create": true, "modify": true, "del": true}},
    {"url": "/agentmonitor", "auth": {"search": true}}, {"url": "/newjob", "auth": {"create": true}},
    {"url": "/joblist", "auth": {"search": true, "operate": true, "modify": true, "del": true}},
    {"url": "/newjobflow", "auth": {"create": true}},
    {"url": "/jobflowlist", "auth": {"search": true, "operate": true, "modify": true, "del": true}},
    {"url": "/calendarmgmt", "auth": {"search": true, "create": true, "modify": true, "del": true}},
    {"url": "/variablemgmt", "auth": {"search": true, "create": true, "modify": true, "del": true}},
    {"url": "/jobflowview", "auth": {"search": true, "operate": true}},
    {"url": "/jobflowviewhistory", "auth": {"search": true}},
    {"url": "/jobview", "auth": {"search": true, "operate": true}},
    {"url": "/jobviewhistory", "auth": {"search": true}}, {"url": "/alarmlist", "auth": {"search": true}},
    {"url": "/syssetup", "auth": {"operate": true, "modify": true}},
    {"url": "/userandpermissions", "auth": {"search": true, "create": true}},
    {"url": "/systemclassmanage", "auth": {"search": true, "create": true, "modify": true, "del": true}},
    {"url": "/log", "auth": {"search": true}}, {"url": "/viewdetail", "auth": {"search": true, "operate": true}}]}}
